### ISSUE TITLE
4.11/4.10 LUNAR CLIENT 注入就黑屏（屏幕很暗）

### ISSUE THREAD

**Issue by sillyHamsterHack** [Vape1337/Vapev4.10-Save#4]
4.11/4.10 LUNAR CLIENT 注入就黑屏（屏幕很暗） 老哥修復一下

**Comment by sillyHamsterHack** [comment]
我可以幫你修復一下（時間自動往前調）

**Comment by Vape1337** [comment]
好的，我测试一下
谢谢你的提交

**Comment by Vape1337** [comment]
> 我可以幫你修復一下（時間自動往前調）

好的，你是哪里人，有什么联系方式？

**Comment by Vape1337** [comment]
> 我可以幫你修復一下（時間自動往前調）

如果你有QQ添加我
我的QQ号：3390428298
