### ISSUE TITLE
软件报毒，请修复一下

### ISSUE THREAD

**Issue by guoyaoyao2011** [Vape1337/Vapev4.10-Save#5]
![image](https://github.com/user-attachments/assets/1494620c-01d9-44df-94f4-bb200ac6d570)
软件报毒，请修复一下

**Comment by Vape1337** [comment]
木马？可是我的源代码是公开的，并且在0.1.1版本我甚至没有打包，直接是py的形式

**Comment by guoyaoyao2011** [comment]
主要不知道为啥这样，729的4.10没事，我单独测试4.10也不行

**Comment by guoyaoyao2011** [comment]
也有毒

**Comment by guoyaoyao2011** [comment]
用着不放心

**Comment by Vape1337** [comment]
你是说729的vape也报毒？

**Comment by Vape1337** [comment]
> 也有毒

好吧，我不知道为什么，可能是因为要链接服务器和打开服务器，然后报了，我稍后反编译Vape loader

**Comment by guoyaoyao2011** [comment]
不是，729不报毒，但是你这里面的4.10报毒，我估计会不会是更改了时间，主要是不敢用eee

**Comment by guoyaoyao2011** [comment]
![image](https://github.com/user-attachments/assets/49215830-ff87-4b55-83d9-99d1dc74cd7f)
这个是runasdate的使用方式

**Comment by guoyaoyao2011** [comment]
![image](https://github.com/user-attachments/assets/4e6bb43f-2234-4943-b22f-7f93be472c2d)
这个是runasdate的使用方式，你看看，这里下载https://www.nirsoft.net/utils/run_as_date.html

**Comment by guoyaoyao2011** [comment]
https://www.virustotal.com/gui/file/69579fc19ae10de3c42722e5b32cb8661829b7e4bb82901e240630ed36d9e9f1?nocache=1
https://www.virustotal.com/gui/file/49ac536d10e9a6bf370d72b802161de8d7074b3090d2252e598f75b1bc78b767?nocache=1
https://www.virustotal.com/gui/file/d5c024857d30059eedeee4f81678e7f77739f36c00a6ea0c7acd2ac3e8009837?nocache=1
https://www.virustotal.com/gui/file/3c977a66ae7c3e80368f5f40f446408c83c39a0ac59ded2352ad0bccb6b6fcdf?nocache=1

**Comment by Vape1337** [comment]
time是改时间的，改的系统时间
del是删除设置的特殊字符
open是打开Vape注入的，我现在没有这个的源码了，以前发过
————————


> ![图像](https://private-user-images.githubusercontent.com/123535134/361181576-4e6bb43f-2234-4943-b22f-7f93be472c2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1NjQ1MjAsIm5iZiI6MTcyNDU2NDIyMCwicGF0aCI6Ii8xMjM1MzUxMzQvMzYxMTgxNTc2LTRlNmJiNDNmLTIyMzQtNDk0My1iMjJmLTdmOTNiZTQ3MmMyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNVQwNTM3MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWUwNTliZjI4Yjk1MjY0NGIxYjFkM2U3ZTAxNzJiZTU3YjVhNDA3ODgxNDFlZDJhNTFkNDA0YzZmNTNiMWM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pLxnTOegSV14mP5pkRwaksCnAZgIoHcK7SlX0JBqB48)这个是runasdate的使用方式，你看看，这里下载 https://www.nirsoft.net/utils/run_as_date.html

我是想把程序javaw的时间改了，因为每个人的java环境不一样
